### ISSUE TITLE
Lokalise download file seems to be broken

### ISSUE THREAD

**Issue by akougblenou** [lokalise/node-lokalise-api#18]
**Describe the bug**
Following the new update it seems that something has been broken on the package because using the download method always returns an error of the form:
```bash
(node:79054) ExperimentalWarning: The dns.promises API is experimental
(node:79054) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
(node:79054) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at got.then (/foundation_lambda_node/lokalise_put_translation/node_modules/@lokalise/node-api/dist/http_client/base.js:37:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:79054) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:79054) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
Basic use of the download method :
```js
const response = await lokaliseApi.files.download(projectId, {format: 'json', "original_filenames": true});
```

**Expected behavior**
I expected the function to return with an object that contains the response of the api (200, with the bundle path or an HTTP error code)

**Your environment:**
 - Node version 10.16.3

**Additional context**
Working on a AWS lambda, testing locally by faking the trigger of the lokalise webhook.

**Comment by bodrovis** [comment]
Hello and thanks for reaching us out! We have tried running the `download` method on different machines but have not seen any issues: it works fine. Actually, the recent release did not make any big changes to this method anyways... It seems like the error is related to the network issues on your side, unfortunately. Could you please try to test it without faking the webhook as it seems the most probable cause? Another small possibility is that this problem is related to Got which is used internally to send requests, though it seems quite unlikely

**Comment by akougblenou** [comment]
Well a bit of the background about the script it was working correctly yesterday at 6.34pm (French time) and this morning it wasn't, but nothing was chnaged on our part.
Both the local version (which mocks the request)and the AWS version (which uses the real webhook) return with the above error. By removing bit of the code we manage to isaolate the fact that when this line was called :
```js
    const response = await lokaliseApi.files.download(projectId, {format: 'json', "original_filenames": true});
```
the error occured.

**Comment by bodrovis** [comment]
Okay, thank you for the clarification. We will investigate.

**Comment by bodrovis** [comment]
By the way, does it work if you downgrade the plugin to the previous 4.x version?

**Comment by akougblenou** [comment]
Haven't tried that be I think me an my team we uncovered the issue.
Our lambda is supposed to work on a trigger of the webhook, because we wanted result fast we checked all the trigger of the webhook.
The lambda downloads the translation files and I believe that downloading the project is equal to exporting it thus triggering the webhook which triggers the lamda... you see what I am getting at here... If there is an error in the lambda the webhook is also going to respond with an error causing our hook to look "spammy", thus probably crashing.
But these are just assumptions from work on my team's part yesterday...

**Comment by bodrovis** [comment]
It may be the case, actually. I spent some time today and yesterday to research this further and honestly I haven't found anything. Right now I've tried installing Node 10.16 but the download is still working fine. Therefore, let's assume that's the problem is with the hook. Still, if this issue will happen under other conditions - please feel free to open a request here or contact the support team at Lokalise site (I'll be able to join conversation there). P.S. It's worth mentioning that Got (we use it to send the requests) doesn't support Node < 10.19 officially https://github.com/sindresorhus/got/blob/master/package.json#L10 Un-officially it should still work with Node < 10.19 but it's something to take a notice of. Cheers!
